version: "3"
services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    #container_name: pq-db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: pq_user
      POSTGRES_PASSWORD: password
      #POSTGRES_DATABASE: app_db
    #volumes:
    #  - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    #container_name: go-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

#volumes:
#  db_data:
#    external: false
